//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class blogEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public blogEntry()
        {
            this.blogTags = new HashSet<blogTag>();
        }
    
        public int id { get; set; }
        public int authorId { get; set; }
        public string blogEntryContent { get; set; }
        public string blogEntryTitle { get; set; }
        public System.DateTime creationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blogTag> blogTags { get; set; }
        public virtual author author { get; set; }
    }
}
