//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalWebsite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CWARDEntities : DbContext
    {
        public CWARDEntities()
            : base("name=CWARDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<blogTag> blogTags { get; set; }
        public virtual DbSet<blogEntry> blogEntries { get; set; }
        public virtual DbSet<loginLog> loginLogs { get; set; }
        public virtual DbSet<author> authors { get; set; }
    }
}
